### ISSUE TITLE
get_resource() - Error in switch(fmt, csv = { : EXPR must be a length 1 vector

### ISSUE THREAD

**Issue by levinemi** [sharlagelfand/opendatatoronto#10]
I'm trying to load the Bike Share Ridership data for 2018 via the opendatatoronto package.  I ran the following:
#Get datasets (called packages) from the Open Data Catalogue by dataset code
#Bike Share Ridership package (https://open.toronto.ca/dataset/bike-share-toronto-ridership-data/)
package_ride <- show_package("7e876c24-177c-4605-9cef-e50dd74c617f") %>% list_package_resources()

#Download the specific data files (called resources) of interest
ride_raw2017 <- package_ride %>% slice(4) %>% get_resource()
ride_raw2018 <- package_ride %>% slice(6) %>% get_resource()

I get the following error: Error in switch(fmt, csv = { : EXPR must be a length 1 vector
![image](https://user-images.githubusercontent.com/61522420/93642740-9532cb00-f9cc-11ea-9b77-9668cc374a3a.png)

Can you help me troubleshoot this issue?  The 2017 dataset which is also a zip file loaded successfully.

Thanks.

**Comment by sharlagelfand** [comment]
Hi @levinemi, apologies for the long, long delay in getting to this. As I mentioned in our email it was something that needed to be fixed in `ckanr`, the package that underlies `opendatatoronto`, and I finally took the time to do so (in the issue linked above).

If you update your version of `opendatatoronto`, it should now work with no issue:

``` r
# Install the updated version first
# install.packages("devtools")
devtools::install_github("sharlagelfand/opendatatoronto", ref = "main")

library(opendatatoronto)
library(dplyr)

package_ride <- show_package("7e876c24-177c-4605-9cef-e50dd74c617f") %>% 
  list_package_resources()

ride_raw2018 <- package_ride %>% 
  filter(name == "Bike Share Ridership 2018") %>%
  get_resource()

names(ride_raw2018)
# [1] "bikeshare2018"                           
# [2] "Bike Share Toronto Ridership_Q1 2018.csv"
# [3] "Bike Share Toronto Ridership_Q2 2018.csv"
# [4] "Bike Share Toronto Ridership_Q3 2018.csv"
# [5] "Bike Share Toronto Ridership_Q4 2018.csv"
```

Thanks, and sorry again for the long wait!

**Comment by levinemi** [comment]
Thanks Sharla.  I'll update the package and try again.
Cheers,
mich
