### ISSUE TITLE
Add civic issues field to package functions

### ISSUE THREAD

**Issue by sharlagelfand** [sharlagelfand/opendatatoronto#3]
the toronto open data team has added a new field, "Civic Issues", to packages, and it would be helpful to add this to the package functions in this package (ha ha, i know).

what needs to be done for this to happen:

* add the `civic_issues` field to `package_res_init` in utils.R (maybe directly after `topics`?)
* add a test in `test-list_packages.R`, `test-search_packages.R`, and `test-show_package.R` to test that this field returns as a character
* re-render the `README.rmd` so that the readme shows this new column.

i will handle re-rendering/updating the pkgdown site on my end :~)

**Comment by HernanGaleano** [comment]
Hi! Does "re-render" mean knitting the README.Rmd file? In that file, the `list_packages(limit = 100)` does not return the package with the title "Marriage Licence Statistics" anymore, it's on the 160th row now.

**Comment by sharlagelfand** [comment]
@HernanGaleano yup, that would mean knitting the README.Rmd file! you're right, using `list_packages()` probably isn't the best thing in this case -- i should probably use `search_packages()` or `show_package()` for that example, thank you!

**Comment by sharlagelfand** [comment]
Closed in #4.
