### ISSUE TITLE
CRAN binary issues to fix

### ISSUE THREAD

**Issue by sharlagelfand** [sharlagelfand/opendatatoronto#7]
* [x] ~**r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-patched-solaris-x86**: "NOTE Namespaces in Imports field not imported from:  ‘readxl’ ‘xml2’ All declared Imports should be used."~ hopefully this is OK - opendatatoronto doesn't use readxl or xml2 directly, but `ckanr::ckan_fetch()` does. however, ckanr only lists them in "Suggests" and throws an error if the user does not have them installed. to reduce friction, i listed them in imports so that everything a user really "needs" is installed when opendatatoronto is
* [x] ~**r-devel-windows-ix86+x86_64**: list_package_resources("1234") threw an error with unexpected message. Expected match: "not found" Actual message: "subscript out of bounds"~ test hits API and should not be run on CRAN -- added `skip_on_cran()`
* [x] ~**r-devel-windows-ix86+x86_64**: warning in building multifile_zip_resources.Rmd~ replaced with a data set that doesn't yield these errors
* [ ] **r-devel-windows-ix86+x86_64**: error in building opendatatoronto.Rmd
* [ ] **r-devel-windows-ix86+x86_64**: error in building spatial_dsata.Rmd

**Edit:** Everything except the NOTE went away once I actually waited the recommended 48 hours 😬. I'll still add `skip_on_cran()` for that test but the rest were 500 errors that went away, so nothing needs to be fixed

**Comment by jennybc** [comment]
If you place a call like `readxl::read_excel` somewhere in your package, it will suppress this NOTE. So, you don't even need to execute the function, just *mention* it. Or if you think that looks too funny, there are other techniques that feel a bit more natural: https://github.com/r-lib/lifecycle/issues/22#issuecomment-534323567

**Comment by sharlagelfand** [comment]
ooh thank you @jennybc! that's super helpful - and feels much less funny than writing an entire paragraph explaining the NOTE to CRAN. ty!!
