### ISSUE TITLE
Attempting to get_resource for some CSVs gives an mapping-related error

### ISSUE THREAD

**Issue by RohanAlexander** [sharlagelfand/opendatatoronto#8]
Hi Sharla,
Thank you for the wonderful package.
I'm having an issue with get_resource() when dealing with some CSVs. 
An example is following the code from the example for the fire incident's page:
https://open.toronto.ca/dataset/fire-incidents/

```
library(opendatatoronto)
library(dplyr)
  
# get package
package <- show_package("64a26694-01dc-4ec3-aa87-ad8509604f50")
package
  
# get all resources for this package
resources <- list_package_resources("64a26694-01dc-4ec3-aa87-ad8509604f50")

# identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
  
# load the first datastore resource as a sample
data <- filter(datastore_resources, row_number()==1) %>% get_resource()
data
```
After the function get_resouce() I am getting an error related to maps, even though the resource is a CSV:
```
Error in rcpp_geojson_to_sf(geojson, expand_geometries) : 
  Not compatible with STRSXP: [type=NULL].
```
I have tried to manually download the data, just to check that it is actually a CSV, and that is fine. Is it possible that there is something in the if else statements in the function that is causing it to think that the file is a geographic format?

I am using version ‘0.1.1’ of opendatatoronto.

**Comment by sharlagelfand** [comment]
thanks for this @RohanAlexander! you're totally right, the way i was checking if a datastore resource was spatial was by seeing if it had [columns named latitude/longitude or a geometry column](https://github.com/sharlagelfand/opendatatoronto/blob/eb967805a170684ab19395555e69f042552ccf19/R/get_resource.R#L89), but then i was only [converting "geometry" columns to the geospatial format](https://github.com/sharlagelfand/opendatatoronto/blob/eb967805a170684ab19395555e69f042552ccf19/R/get_resource.R#L100), so resources that didn't have "geometry" but had latitude/longitude (like the one you've indicated above) were getting left behind!

here's an example (with another CSV with latitude/longitude column names, but is much smaller so faster to reprex 😄), with the version on CRAN:

``` r
library(opendatatoronto)
library(dplyr)

# https://open.toronto.ca/dataset/traffic-cameras/

list_package_resources("https://open.toronto.ca/dataset/traffic-cameras/") %>%
  filter(name == "Traffic Camera List (CSV)") %>%
  get_resource()
#> Error in rcpp_geojson_to_sf(geojson, expand_geometries): Not compatible with STRSXP: [type=NULL].
```

i've updated the code on github now, and with that version it works fine:

``` r
library(opendatatoronto)
library(dplyr)

# https://open.toronto.ca/dataset/traffic-cameras/

list_package_resources("https://open.toronto.ca/dataset/traffic-cameras/") %>%
  filter(name == "Traffic Camera List (CSV)") %>%
  get_resource()
#> # A tibble: 280 x 12
#>    `_id` `Camera Number` Latitude Longitude `Main Road` `Cross Street`
#>    <int> <chr>              <dbl>     <dbl> <chr>       <chr>         
#>  1     1 Camera8001          43.6     -79.4 YORK ST     BREMNER BLVD  
#>  2     2 Camera8002          43.6     -79.4 BREMNER BL… LOWER SIMCOE …
#>  3     3 Camera8003          43.6     -79.4 JARVIS ST   FRONT ST E    
#>  4     4 Camera8004          43.6     -79.4 UNIVERSITY… FRONT ST W / …
#>  5     5 Camera8005          43.6     -79.4 FRONT ST W  SIMCOE ST / L…
#>  6     6 Camera8006          43.6     -79.4 FRONT ST W  JOHN ST / PRI…
#>  7     7 Camera8007          43.6     -79.4 SPADINA AVE FRONT ST W    
#>  8     8 Camera8008          43.6     -79.4 BATHURST ST FRONT ST W    
#>  9     9 Camera8009          43.7     -79.4 JARVIS ST   KING ST E     
#> 10    10 Camera8010          43.7     -79.4 KING ST E   PARLIAMENT ST 
#> # … with 270 more rows, and 6 more variables: Group <chr>, `Traffic
#> #   Image` <chr>, `North Reference Static Image` <chr>, `East Reference
#> #   Static Image` <chr>, `South Reference Static Image` <chr>, `West
#> #   Reference Static Image` <chr>
```

and works for the resource you indicated as well.

i may eventually look into converting non-geojson resources with latitude/longitude columns to sf objects, but for now would suggest using `sf::st_as_sf()` on the tibble if you're interested in using it geospatially.

**Comment by RohanAlexander** [comment]
Hi @sharlagelfand ,
Sorry, I'm just following up on this one to say thank you very much for updating the package so quickly. I hadn't realized that you'd dealt with it - I saw the email notification from GitHub but I just thought it was an acknowledgement of opening an issue or something. Sorry.
Anyway. Thank you very much for the update to what was already a wonderful package. Looking forward to continuing to use it in the future.
Rohan

**Comment by sharlagelfand** [comment]
all good @RohanAlexander! i thought you may not have seen it - that's what i get for making the fix too fast 🙊 😄 hope it's helpful!
